/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.incredas.spring.starter;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

}
