/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.incredas.spring.starter;

import dev.incredas.spring.starter.Library;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class LibraryTest {

    @Test
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

}
