name: Build and Publish

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and Publish
        run: ./gradlew publish

        env:
          USERNAME_GITHUB: ${{ secrets.USERNAME_GITHUB }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}